### ISSUE TITLE
[Bug]: new APIKey page hangs for over 10 secs for the creation and never get stage apiKey.

### ISSUE THREAD

**Issue by tanyutu** [spaship/spaship#395] opened 2020-04-23 11:53 UTC
## Steps to reproduce:
1. login dev
2. click create new API Key
3. fill name and choose all the environments 
4. click create APIKey button
Actual:
The page hangs for more than 10 secs, and never get the stage apikey

## Screenshots:
<img width="1440" alt="Screen Shot 2020-04-23 at 7 48 49 PM" src="https://user-images.githubusercontent.com/28708431/80096380-0dbb6a00-859c-11ea-986a-c1c91d03bc24.png">

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

**Comment by kunyan** [comment] 2020-04-24 03:31
@tanyutu This issue looks not a bug, there has some problems on server side

<img width="681" alt="Screen Shot 2020-04-24 at 11 30 06 AM" src="https://user-images.githubusercontent.com/752130/80172244-11440500-861f-11ea-92d9-9bda8c3e099c.png">

The Database looks has some problems. I'll try to make it work

**Comment by kunyan** [comment] 2020-04-24 03:33
The database pod has some error, I'll restart it
<img width="1111" alt="Screen Shot 2020-04-24 at 11 33 00 AM" src="https://user-images.githubusercontent.com/752130/80172362-6718ad00-861f-11ea-8dfa-1c46ca9d85e1.png">
<img width="1191" alt="Screen Shot 2020-04-24 at 11 33 11 AM" src="https://user-images.githubusercontent.com/752130/80172368-6aac3400-861f-11ea-83e1-58bf3add26e3.png">

**Comment by kunyan** [comment] 2020-04-24 03:47
Database recovered. This issue should be disappeared. close this

**Closed by kunyan** 2020-04-24 03:47 UTC
Labels: bug
